version: "3.9"

services:
  app:
    build: .
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - .:/home/app:rw
    ports:
      - 3456:3456
